# Generated by Django 5.2 on 2025-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.CharField(default='device-gamepad', max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.favoritegenre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.platform'),
        ),
    ]
