# Generated by Django 5.2 on 2025-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favoritegenre_platform_userprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
