# Generated by Django 5.2 on 2025-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_by', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=255)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='games.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='games.tag')),
            ],
        ),
    ]
