# Generated by Django 5.2 on 2025-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='game',
            name='age_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
