# Generated by Django 5.2 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_average_rating_game_age_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
