# Generated by Django 5.2 on 2025-10-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
