# Generated by Django 5.2 on 2025-10-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='linux_requirements_minimum',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mac_requirements_minimum',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pc_requirements_minimum',
            field=models.TextField(blank=True),
        ),
    ]
